import type { PrismaClient } from "@prisma/client";
import { CATALOG_SEED } from "./catalog";

export const SUPPLIER_SEED = [
  {
    slug: "frantoio-del-crinale",
    name: "Frantoio del Crinale",
    company: "Frantoio del Crinale S.n.c.",
    street: "Strada del Crinale 14",
    city: "Dolcedo",
    postal: "18020",
    phone: "+390183280014",
    email: "spedizioni@frantoiodelcrinale.it",
  },
  {
    slug: "oliveto-di-taggia",
    name: "Oliveto di Taggia",
    company: "Oliveto di Taggia",
    street: "Via Soleri 28",
    city: "Taggia",
    postal: "18018",
    phone: "+39018447588",
    email: "ordini@olivetoditaggia.it",
  },
  {
    slug: "pestoteca-pra",
    name: "Pestoteca di Pra",
    company: "Pestoteca di Pra",
    street: "Via Pra 41",
    city: "Genova",
    postal: "16157",
    phone: "+39010380112",
    email: "mortaio@pestotecapra.it",
  },
  {
    slug: "apicoltura-millesimo",
    name: "Apicoltura Millesimo",
    company: "Apicoltura Millesimo di Brea",
    street: "Via delle Arnie 3",
    city: "Millesimo",
    postal: "17017",
    phone: "+39019754003",
    email: "ordini@apicolturamillesimo.it",
  },
  {
    slug: "composta-del-fico",
    name: "Composta del Fico",
    company: "Composta del Fico",
    street: "Strada dei Fichi 6",
    city: "Cervo",
    postal: "18010",
    phone: "+39018340821",
    email: "vasi@compostadelfico.it",
  },
  {
    slug: "erbe-della-macchia",
    name: "Erbe della Macchia",
    company: "Erbe della Macchia",
    street: "Via della Macchia 2",
    city: "Andora",
    postal: "17051",
    phone: "+39018268140",
    email: "sale@erbedellamacchia.it",
  },
  {
    slug: "mulino-delle-castagne",
    name: "Mulino delle Castagne",
    company: "Mulino delle Castagne",
    street: "Via del Mulino 9",
    city: "Calizzano",
    postal: "17057",
    phone: "+39019786014",
    email: "farina@mulinocastagne.it",
  },
  {
    slug: "torrefazione-della-macina",
    name: "Torrefazione della Macina",
    company: "Torrefazione della Macina",
    street: "Via Paleocapa 22",
    city: "Savona",
    postal: "17100",
    phone: "+39019820114",
    email: "lotti@macina.coffee",
  },
  {
    slug: "erboristeria-crinale",
    name: "Erboristeria del Crinale",
    company: "Erboristeria del Crinale",
    street: "Piazza della Chiesa 4",
    city: "Pigna",
    postal: "18037",
    phone: "+39018424109",
    email: "erbe@crinale.liguria.it",
  },
  {
    slug: "cioccolateria-albenga",
    name: "Cioccolateria di Albenga",
    company: "Cioccolateria di Albenga",
    street: "Via Medaglie d’Oro 15",
    city: "Albenga",
    postal: "17031",
    phone: "+39018254190",
    email: "tavolette@cioccolatoalbenga.it",
  },
  {
    slug: "forno-del-miele",
    name: "Forno del Miele",
    company: "Forno del Miele",
    street: "Via Roma 18",
    city: "Millesimo",
    postal: "17017",
    phone: "+39019754122",
    email: "forno@fornodelmiele.it",
  },
  {
    slug: "caseificio-pennavaire",
    name: "Caseificio Pennavaire",
    company: "Caseificio Pennavaire",
    street: "Strada della Valle 7",
    city: "Castelvecchio di Rocca Barbena",
    postal: "17010",
    phone: "+39018279033",
    email: "forme@pennavaire.it",
  },
  {
    slug: "cantina-della-costa",
    name: "Cantina della Costa",
    company: "Cantina della Costa",
    street: "Strada del Rossese 16",
    city: "Dolceacqua",
    postal: "18035",
    phone: "+39018420641",
    email: "cantina@costarossese.it",
  },
  {
    slug: "acetificio-noli",
    name: "Acetificio di Noli",
    company: "Acetificio di Noli",
    street: "Via Vignassa 11",
    city: "Noli",
    postal: "17026",
    phone: "+39019748940",
    email: "botti@acetificionoli.it",
  },
  {
    slug: "distilleria-mirto",
    name: "Distilleria del Mirto",
    company: "Distilleria del Mirto",
    street: "Via del Porto 8",
    city: "Loano",
    postal: "17025",
    phone: "+39019675012",
    email: "alambicco@distilleriamirto.it",
  },
  {
    slug: "vermutteria-della-rada",
    name: "Vermutteria della Rada",
    company: "Vermutteria della Rada",
    street: "Corso Italia 33",
    city: "Savona",
    postal: "17100",
    phone: "+39019820255",
    email: "erbe@vermutteriarada.it",
  },
  {
    slug: "legatoria-costa",
    name: "Legatoria Costa",
    company: "Legatoria Costa",
    street: "Vicolo del Cuoio 7",
    city: "Albenga",
    postal: "17031",
    phone: "+39018255107",
    email: "bottega@legatoriacosta.it",
  },
  {
    slug: "officina-del-mallo",
    name: "Officina del Mallo",
    company: "Officina del Mallo",
    street: "Via del Molo 9",
    city: "Noli",
    postal: "17026",
    phone: "+39019748912",
    email: "inchiostro@officinalmallo.it",
  },
  {
    slug: "cartiera-albenga",
    name: "Cartiera di Albenga",
    company: "Cartiera di Albenga",
    street: "Via della Cartiera 5",
    city: "Albenga",
    postal: "17031",
    phone: "+39018255240",
    email: "fogli@cartieraalbenga.it",
  },
  {
    slug: "pelletteria-del-porto",
    name: "Pelletteria del Porto",
    company: "Pelletteria del Porto",
    street: "Calata Cuneo 12",
    city: "Imperia",
    postal: "18100",
    phone: "+39018365077",
    email: "cuoio@pelletteriadelporto.it",
  },
  {
    slug: "tessitura-dellorlo",
    name: "Tessitura dell’Orlo",
    company: "Tessitura dell’Orlo",
    street: "Corso Repubblica 40",
    city: "Ventimiglia",
    postal: "18039",
    phone: "+39018435122",
    email: "lino@tessituradellorlo.it",
  },
  {
    slug: "argenteria-sanremo",
    name: "Argenteria di Sanremo",
    company: "Argenteria di Sanremo",
    street: "Via Palazzo 8",
    city: "Sanremo",
    postal: "18038",
    phone: "+39018450733",
    email: "laboratorio@argenteriasanremo.it",
  },
  {
    slug: "ramificio-oneglia",
    name: "Ramificio di Oneglia",
    company: "Ramificio di Oneglia",
    street: "Via Bonfante 19",
    city: "Imperia",
    postal: "18100",
    phone: "+39018376720",
    email: "rame@ramificiooneglia.it",
  },
  {
    slug: "coltelleria-san-siro",
    name: "Coltelleria San Siro",
    company: "Coltelleria San Siro",
    street: "Via San Siro 6",
    city: "Sanremo",
    postal: "18038",
    phone: "+39018450918",
    email: "lame@coltelleriasansiro.it",
  },
  {
    slug: "legno-di-ulivo",
    name: "Legno di Ulivo",
    company: "Legno di Ulivo",
    street: "Strada degli Ulivi 3",
    city: "Dolcedo",
    postal: "18020",
    phone: "+39018328055",
    email: "taglieri@legnoulivo.it",
  },
  {
    slug: "vetreria-finale",
    name: "Vetreria di Finale",
    company: "Vetreria di Finale",
    street: "Via Garibaldi 14",
    city: "Finale Ligure",
    postal: "17024",
    phone: "+39019692108",
    email: "fornace@vetreriafinale.it",
  },
  {
    slug: "fornace-albissola",
    name: "Fornace di Albissola",
    company: "Fornace di Albissola",
    street: "Via Poggi 21",
    city: "Albissola Marina",
    postal: "17012",
    phone: "+39019482330",
    email: "maiolica@fornacealbissola.it",
  },
  {
    slug: "lanificio-di-costa",
    name: "Lanificio di Costa",
    company: "Lanificio di Costa",
    street: "Via del Telaio 5",
    city: "Pieve di Teco",
    postal: "18026",
    phone: "+39018336108",
    email: "tessuti@lanificiodicosta.it",
  },
  {
    slug: "setificio-ventimiglia",
    name: "Setificio di Ventimiglia",
    company: "Setificio di Ventimiglia",
    street: "Via Hanbury 19",
    city: "Ventimiglia",
    postal: "18039",
    phone: "+39018435188",
    email: "seta@setificiovtm.it",
  },
  {
    slug: "cereria-delle-arnie",
    name: "Cereria delle Arnie",
    company: "Cereria delle Arnie",
    street: "Contrada delle Api 2",
    city: "Calice Ligure",
    postal: "17020",
    phone: "+39019759021",
    email: "cera@cereriadellearnie.it",
  },
  {
    slug: "saponificio-alloro",
    name: "Saponificio all’Alloro",
    company: "Saponificio all’Alloro",
    street: "Via Soleri 11",
    city: "Taggia",
    postal: "18018",
    phone: "+39018447520",
    email: "saponi@alloro.liguria.it",
  },
  {
    slug: "profumeria-delle-foglie",
    name: "Profumeria delle Foglie",
    company: "Profumeria delle Foglie",
    street: "Via Tommaso Schiva 9",
    city: "Imperia",
    postal: "18100",
    phone: "+39018365901",
    email: "estratti@foglie.liguria.it",
  },
  {
    slug: "oreficeria-del-capo",
    name: "Oreficeria del Capo",
    company: "Oreficeria del Capo",
    street: "Via Matteotti 4",
    city: "Bordighera",
    postal: "18012",
    phone: "+39018426270",
    email: "laboratorio@oreficeriadelcapo.it",
  },
] as const;

export type SupplierSlug = (typeof SUPPLIER_SEED)[number]["slug"];

export const PRODUCT_SUPPLIER = Object.fromEntries(
  CATALOG_SEED.map((product) => [product.slug, product.supplierSlug]),
) as Record<string, SupplierSlug>;

export function formatSupplierSeat(supplier: {
  name: string;
  street: string;
  postal: string;
  city: string;
}) {
  return `${supplier.name} · ${supplier.street}, ${supplier.postal} ${supplier.city}`;
}

export async function upsertSuppliers(db: PrismaClient) {
  const bySlug = new Map<string, { id: string; slug: string }>();
  for (const supplier of SUPPLIER_SEED) {
    const row = await db.supplier.upsert({
      where: { slug: supplier.slug },
      create: { ...supplier },
      update: {
        name: supplier.name,
        company: supplier.company,
        street: supplier.street,
        city: supplier.city,
        postal: supplier.postal,
        phone: supplier.phone,
        email: supplier.email,
      },
    });
    bySlug.set(row.slug, row);
  }
  return bySlug;
}

export async function attachCatalogSuppliers(db: PrismaClient) {
  const bySlug = await upsertSuppliers(db);
  for (const product of CATALOG_SEED) {
    const supplier = bySlug.get(product.supplierSlug);
    if (!supplier) continue;
    await db.product.updateMany({
      where: { slug: product.slug },
      data: { supplierId: supplier.id },
    });
  }
  return bySlug;
}
